baseURL = "https://kai.ge"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "凯哥的个人网站"                    # site title  # 网站标题
theme = "hugo-theme-zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname
publishdir = "./"
contentdir = "content"
[author]                             # essential                     # 必需
  name = "凯哥"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "收藏"
  weight = 35
  identifier = "fav"
  url = "/fav"  
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "kai.ge"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "Invert,always invert."                                          # site's footer slogan  # 网站页脚标语
  keywords = ["kai.ge","凯哥博客", "blog","hugo"]                                  # site's keywords  # 网站关键字
  description = "凯哥的个人网站"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  github = "https://github.com/udbmnm"
  twitter = "https://twitter.com/udbmnm"
